//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane2
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayitlar
    {
        public int kayitID { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> kitapID { get; set; }
        public Nullable<System.DateTime> alişTarih { get; set; }
        public Nullable<System.DateTime> teslimTarih { get; set; }
        public Nullable<bool> teslimDurum { get; set; }
    
        public virtual kaynaklar kaynaklar { get; set; }
        public virtual uyeler uyeler { get; set; }
    }
}
