//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane2
{
    using System;
    using System.Collections.Generic;
    
    public partial class kaynaklar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kaynaklar()
        {
            this.kayitlar = new HashSet<kayitlar>();
        }
    
        public int kitapID { get; set; }
        public string kitapAd { get; set; }
        public string kitapYazar { get; set; }
        public string kitapYayınevi { get; set; }
        public Nullable<int> kitapSayfa { get; set; }
        public Nullable<System.DateTime> kitapTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kayitlar> kayitlar { get; set; }
    }
}
