//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphane2
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int personelID { get; set; }
        public string personelAd { get; set; }
        public string personelSoyad { get; set; }
        public string personelTc { get; set; }
        public string personelTel { get; set; }
        public string personelMail { get; set; }
        public string personelKullaniciAdi { get; set; }
        public string personelŞifre { get; set; }
    }
}
